(require "interpreter.rkt")

(interpreter aprog)
(interpreter bprog)
(interpreter cprog)
(interpreter dprog)
(interpreter eprog)
(interpreter fprog)
(interpreter gprog)
(interpreter hprog)
(interpreter iprog)
